name: ml-env
channels:
  - conda-forge
dependencies:
  - conda-forge::otter-grader=6.0.4
  - conda-forge::ucimlrepo=0.0.7
  - ipykernel=6.29.3
  - ipython=8.18.1
  - ipywidgets=8.1.1
  - kagglehub=0.3.5
  - keras=2.15.0
  - librosa=0.10.1
  - matplotlib=3.8.0
  - numpy=1.24.3
  - openpyxl=3.1.2
  - pandas=2.1.4
  - pip
  - python=3.10
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - seaborn=0.13.0
  - spotipy=2.23.0
  - statsmodels=0.14.1
  - xgboost=2.0.3
  - geopandas
  - ca-certificates
  - certifi
  - openssl
  - rioxarray
prefix: /Users/hayleeoyler/miniforge3/envs/ml-env
